import { test, expect } from '@playwright/test';
test('stacked service particle study responds and respects reduced motion', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.locator('.services__slot')).toHaveCount(4);
  await expect(page.locator('[data-sculpture]')).toHaveCount(0);
  const field = page.locator('[data-particle-field]');
  await expect(field).toHaveCount(1);
  await field.scrollIntoViewIfNeeded();
  await expect(field).toHaveAttribute('data-ready', 'true');
  const still = await field.locator('canvas').evaluate(canvas => (canvas as HTMLCanvasElement).toDataURL());
  await page.waitForTimeout(150);
  expect(await field.locator('canvas').evaluate(canvas => (canvas as HTMLCanvasElement).toDataURL())).toBe(still);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await field.scrollIntoViewIfNeeded();
  const box = await field.boundingBox();
  await page.mouse.move(box!.x + box!.width * .65, box!.y + box!.height * .45);
  await expect(field).toHaveAttribute('data-interacting', 'true');
  await page.mouse.move(0, 0);
  await expect(field).toHaveAttribute('data-interacting', 'false');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 390, height: 844 });
  await field.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
